language: python
python:
- '3.5'
install:
- pip install --upgrade .
script: python setup.py test
notifications:
  email: false
env:
  secure: u8e2bfezI7y1R4wvND4uZj0lXqvyAT/sceI9Rfjf4Qs2q/Zsy7i5uIOhp05AqwwStYUhIB9fA1ul22C5MOpTreum7pA5GdZ4qmFuqJFW0t+4+ozGg8LYk/Z3Pq2YIQXGnbM+h6itx3DVvM8ZG3Dslyz8Ig4Ivng2vDUhfC1v1RK9fpbYtKskjZRz5pvVk9hMVonM5VjsoqLN6SuHgm+Cawdy/r6Lp+H/BWdQKn5S3pREQ+gBJz2x4xK7UgYXsKvZ3JDi14ZMVXZ74nWc9KxvxouhOk0Z9ElXXbhOAYu72mOu5DrZjwcWbxQTVQsjRnsKYz+ejlfTA9hi1kDqKk+TMR6MfHnO6XX7biVcEs7Odo0qzV2cO9YYw0i1nN/Bhfvz6y2ex9adbLFLH60qmlbhL0LPw7yVx/LyGXlUm6DSKanb43H3vruSloPxif/8h2fj7s7eTwIkR0GJ21GZW6Jhk5Hbvy3RBI1umQ9bpFt1xW0acu7uNWJE/LLc29sPiRAjpqQC+SyiNNJnZ0ASUQrPo4uhZVeTUchX0prmqvk8ir6DuGarymH5WoRFF+Y/KrNhVl3upWK7lTdX7lpxHNVoemYjjS2BEoBUjHGw4+eLozh3myrcXiZvwoZ7E4gs/bKqJyN19/GUZXoieYdJ4QVneTyDKOar4cJ3EqYEsBCPCdI=
